PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS peers (
  name TEXT PRIMARY KEY,
  pubkey TEXT UNIQUE NOT NULL,
  ip6 TEXT UNIQUE NOT NULL,
  created_at INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS meta (
  k TEXT PRIMARY KEY,
  v TEXT NOT NULL
);
INSERT OR IGNORE INTO meta(k,v) VALUES('last_id','1');
